### ISSUE TITLE
Any way to evaluate the quality of the data block?

### ISSUE THREAD

**Issue by bg2bhc** [geeanlooca/deepspace-turbo#6]
Hi Gianluna,

Thank you very much for your excellent work!

I am Wei Mingchuan from Harbin Institute of Technology. I am working on a lunar formation satellite project which will launch 2 micro-satellites to lunar helical orbit later this year. I build a GNU Radio OOT module for the downlink reception of the satellites, with your codes for turbo: https://github.com/bg2bhc/gr-dslwp/

During my recent tests I found that at low SNR sometimes the PLL of the receiver may faile before finished receiving a data block, this means the left half would be very unreliable. At this time turbo decoder will try to fix the errors but generate more errors. Is there any way to evaluate the quality of the data block?

Thank you very much!

Best Regards,

Wei Mingchuan

**Comment by geeanlooca** [comment]
Hi Wei,
I'm glad you found my library useful. 
I'm not sure what you mean by evaluating the quality of the data block, but to improve the bit error rate in case of a missing part of the packet you could modify the decoding algorithm to accept a packet length different from the one set when initializing the turbo code. If your packet length is L you can then pass L to the decoding function when you receive the full packet and L' < L when you receive only a part of the packet. If you don't do that the BCJR algorithm will also take the missing part of the packet into account when deciding for the first part of the packet, so the BER will be higher than expected.

**Comment by bg2bhc** [comment]
Thank you very much for your reply! Will try to pass only part of the packet. For "the quality of the data block", I meant if there is a parameter shows the confidence of the decoded packet, or number of bits that was corrected, or something else like this.
Thank you again!

**Comment by geeanlooca** [comment]
Oh ok I understand now. You should take a look at the `convcode_extrinsic` function in `libconvcodes.c`. Near the end of the function, the decision process is based on this rule 

```
decoded = malloc(packet_length * sizeof *decoded);
        for (int i = 0; i < packet_length; ++i) {
            double one = app[1][i] + extrinsic[1][i];
            double zero = app[0][i] + extrinsic[0][i];
            decoded[i] =  one > zero;
        }
```

So basically, the variables `one` and `zero` contain the confidence that the received symbol is a `1` or a `0`, respectively. You could add a return value to this function to get the vector of `one` and `zero` for each bit, or their difference (Log-Likelihood Ratio, LLR). If the LLR value is close to 0 that means that there is a lot of uncertainty on that particular bit. Since this function is called iteratively in the Turbo decoding function, you have to get this vector for the last call of to this function, that is when the hard decision is done. From there you could get an estimate of the confidence of the entire packet by averaging these values on the entire packet or using a different "cost" function, such as the number of bits with a LLR value close to 0 more than a certain threshold.

**Comment by bg2bhc** [comment]
This is what I want! Thank you very much Gianluna!
